#!/usr/bin/env bash
set -e

# export these variables
declare -x GoNotoAncient
declare -x GoNotoCurrent
declare -x GoNotoCurrentSerif
declare -x GoNotoAncientSerif

declare -x GoNotoAfricaMiddleEast
declare -x GoNotoSouthAsia
declare -x GoNotoAsiaHistorical
declare -x GoNotoSouthEastAsia
declare -x GoNotoEastAsia
declare -x GoNotoEuropeAmericas

GoNotoAncient=(
    "NotoSans-Bold.ttf"
    # 'GoNotoAsiaHistorical.ttf': [
    "NotoSansBhaiksuki-Bold.ttf"
    "NotoSansBrahmi-Bold.ttf"
    "NotoSansGrantha-Bold.ttf"
    "NotoSansKaithi-Bold.ttf"
    "NotoSansKharoshthi-Bold.ttf"
    "NotoSansKhudawadi-Bold.ttf"
    "NotoSansMahajani-Bold.ttf"
    "NotoSansModi-Bold.ttf"
    "NotoSansMultani-Bold.ttf"
    "NotoSansNandinagariSubset-Bold.ttf"
    "NotoSansOldSogdian-Bold.ttf"
    "NotoSansOldTurkic-Bold.ttf"
    "NotoSansPhags-Pa-Bold.ttf"
    "NotoSansSharada-Bold.ttf"
    "NotoSansSiddham-Bold.ttf"
    "NotoSansSogdian-Bold.ttf"
    "NotoSansSoraSompeng-Bold.ttf"
    "NotoSansSoyombo-Bold.ttf"
    "NotoSansSylotiNagri-Bold.ttf"
    "NotoSansTakri-Bold.ttf"
    "NotoSansTirhuta-Bold.ttf"
    "NotoSansZanabazarSquare-Bold.ttf"
    "NotoSerifAhom-Bold.ttf"
    "NotoSerifDograSubset-Bold.ttf"
    "NotoSerifKhojki-Bold.ttf"
    "NotoSerifDivesAkuru-Bold.ttf"
    "NotoSerifMakasar-Bold.ttf"
    # 'GoNotoEuropeAmericas.ttf': [
    "NotoSansCaucasianAlbanian-Bold.ttf"
    "NotoSansCarian-Bold.ttf"
    "NotoSansCanadianAboriginal-Bold.ttf"
    "NotoSansCypriot-Bold.ttf"
    "NotoSansCyproMinoan-Bold.ttf"
    "NotoSansGlagolitic-Bold.ttf"
    "NotoSansLinearA-Bold.ttf"
    "NotoSansLinearB-Bold.ttf"
    "NotoSansLycian-Bold.ttf"
    "NotoSansLydian-Bold.ttf"
    "NotoSansOldItalic-Bold.ttf"
    "NotoSansRunic-Bold.ttf"
    "NotoSansOldHungarian-Bold.ttf"
    "NotoSansGothic-Bold.ttf"
    "NotoSansElbasan-Bold.ttf"
    "NotoSansVithkuqi-Bold.ttf"
    "NotoSansOgham-Bold.ttf"
    "NotoSansOldPermic-Bold.ttf"
    "NotoSansShavian-Bold.ttf"
    "NotoSansDuployan-Bold.ttf"
    "NotoSansMayanNumerals-Bold.ttf"
    # 'GoNotoAfricaMiddleEast.ttf': [
    "NotoSansBamum-Bold.ttf"   # Bamum Supplement is historical
    "NotoSansOldNorthArabian-Bold.ttf"
    "NotoSansOldSouthArabian-Bold.ttf"
    "NotoSansPhoenician-Bold.ttf"
    "NotoSansImperialAramaic-Bold.ttf"
    "NotoSansManichaean-Bold.ttf"
    "NotoSansInscriptionalParthian-Bold.ttf"
    "NotoSansInscriptionalPahlavi-Bold.ttf"
    "NotoSansPsalterPahlavi-Bold.ttf"
    "NotoSansAvestan-Bold.ttf"
    "NotoSansChorasmian-Bold.ttf"
    "NotoSansElymaic-Bold.ttf"
    "NotoSansNabataean-Bold.ttf"
    "NotoSansPalmyrene-Bold.ttf"
    "NotoSansHatran-Bold.ttf"
    # Cuneiform and Hieroglyphs
    "NotoSansCuneiform-Bold.ttf"
    "NotoSansUgaritic-Bold.ttf"
    "NotoSansOldPersian-Bold.ttf"
    "NotoSansEgyptianHieroglyphs-Bold.ttf"
    "NotoSansMeroitic-Bold.ttf"
    "NotoSansAnatolianHieroglyphs-Bold.ttf"
    # 'GoNotoEastAsia.ttf': [
    "NotoSansMarchen-Bold.ttf"
    "NotoSerifTangutSubset-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoCurrent=(
    # It's recommended to put NotoSans-Bold.ttf as the first element in the
    # list to maximize the amount of meta data retained in the final merged font.
    # ------- South Asia ---------
    "NotoSans-Bold.ttf"
    "NotoSansArabic-Bold.ttf" # "NotoNastaliqUrdu-Bold.ttf"
    "NotoSansBengali-Bold.ttf"
    "NotoSansChakma-Bold.ttf"
    "NotoSansDevanagari-Bold.ttf"
    "NotoSansGujarati-Bold.ttf"
    "NotoSansGunjalaGondi-Bold.ttf"
    "NotoSansGurmukhi-Bold.ttf"
    "NotoSansKannada-Bold.ttf"
    "NotoSansLepcha-Bold.ttf"
    "NotoSansLimbu-Bold.ttf"
    "NotoSansMalayalam-Bold.ttf"
    "NotoSansMasaramGondi-Bold.ttf"
    "NotoSansMeeteiMayek-Bold.ttf"
    "NotoSansMro-Bold.ttf"
    "NotoSansNewa-Bold.ttf"
    "NotoSansOlChiki-Bold.ttf"
    "NotoSansOriya-Bold.ttf"
    "NotoSansSaurashtra-Bold.ttf"
    "NotoSansSinhala-Bold.ttf"
    "NotoSansTamil-Bold.ttf"
    "NotoSansTangsa-Bold.ttf"
    "NotoSansTelugu-Bold.ttf"
    "NotoSansThaana-Bold.ttf"
    "NotoSerifTibetanSubset-Bold.ttf"
    "NotoSerifToto-Bold.ttf"
    "NotoSansWancho-Bold.ttf"
    "NotoSansWarangCiti-Bold.ttf"
    # SE Asia
    "NotoSansBalinese-Bold.ttf"
    "NotoSansBatak-Bold.ttf"
    "NotoSansBuginese-Bold.ttf"
    "NotoSansBuhid-Bold.ttf"
    "NotoSansCham-Bold.ttf"
    "NotoSansHanifiRohingya-Bold.ttf"
    "NotoSansHanunoo-Bold.ttf"
    "NotoSansJavanese-Bold.ttf"
    "NotoSansKayahLi-Bold.ttf"
    "NotoSansKhmer-Bold.ttf"
    "NotoSansLao-Bold.ttf"
    "NotoSansMyanmar-Bold.ttf"
    "NotoSansNewTaiLue-Bold.ttf"
    "NotoSansPahawhHmong-Bold.ttf"
    "NotoSansPauCinHau-Bold.ttf"
    "NotoSansRejang-Bold.ttf"
    "NotoSansSundanese-Bold.ttf"
    "NotoSansTagalog-Bold.ttf"
    "NotoSansTagbanwa-Bold.ttf"
    "NotoSansTaiLe-Bold.ttf"
    "NotoSansTaiTham-Bold.ttf"
    "NotoSansTaiViet-Bold.ttf"
    "NotoSansThai-Bold.ttf"
    "NotoSansLisu-Bold.ttf"
    # 'GoNotoEuropeAmericas.ttf': [
    "NotoSansArmenian-Bold.ttf"
    "NotoSansCherokee-Bold.ttf"
    "NotoSansCoptic-Bold.ttf"
    "NotoSansDeseret-Bold.ttf"
    "NotoSansGeorgian-Bold.ttf"
    "NotoSansOsage-Bold.ttf"
    # 'GoNotoAfricaMiddleEast.ttf': [
    "NotoSansAdlam-Bold.ttf"
    "NotoSansBamum-Bold.ttf"
    "NotoSansBassaVah-Bold.ttf"
    "NotoSansHebrew-Bold.ttf"
    "NotoSansSyriac-Bold.ttf"
    "NotoSansSamaritan-Bold.ttf"
    "NotoSansMandaic-Bold.ttf"
    "NotoSerifYezidi-Bold.ttf"
    "NotoSansEthiopic-Bold.ttf"
    "NotoSansOsmanya-Bold.ttf"
    "NotoSansTifinagh-Bold.ttf"
    "NotoSansNKo-Bold.ttf"
    "NotoSansVai-Bold.ttf"
    "NotoSansMendeKikakui-Bold.ttf"
    "NotoSansMedefaidrin-Bold.ttf"
    # 'GoNotoEastAsia.ttf': [
    "NotoSansCJKjpSubset-Bold.ttf"
    "NotoSansCJKkrSubset-Bold.ttf"
    "NotoSansCJKscSubset-Bold.ttf"
    "NotoSansMongolianSubset-Bold.ttf"
    "NotoSansYi-Bold.ttf"
    "NotoSansNushuSubset-Bold.ttf" # Not exactly contemporary use but just 402 glyphs
    "NotoSansMiao-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoAfricaMiddleEast=(
    "NotoSans-Bold.ttf"
    "NotoNaskhArabic-Bold.ttf" # or "NotoSansArabic-Bold.ttf"
    "NotoSansAdlam-Bold.ttf"
    "NotoSansBamum-Bold.ttf"
    "NotoSansBassaVah-Bold.ttf"
    "NotoSansHebrew-Bold.ttf"
    "NotoSansSyriac-Bold.ttf"
    "NotoSansSamaritan-Bold.ttf"
    "NotoSansMandaic-Bold.ttf"
    "NotoSerifYezidi-Bold.ttf"
    # Historical scripts
    "NotoSansOldNorthArabian-Bold.ttf"
    "NotoSansOldSouthArabian-Bold.ttf"
    "NotoSansPhoenician-Bold.ttf"
    "NotoSansImperialAramaic-Bold.ttf"
    "NotoSansManichaean-Bold.ttf"
    "NotoSansInscriptionalParthian-Bold.ttf"
    "NotoSansInscriptionalPahlavi-Bold.ttf"
    "NotoSansPsalterPahlavi-Bold.ttf"
    "NotoSansAvestan-Bold.ttf"
    "NotoSansChorasmian-Bold.ttf"
    "NotoSansElymaic-Bold.ttf"
    "NotoSansNabataean-Bold.ttf"
    "NotoSansPalmyrene-Bold.ttf"
    "NotoSansHatran-Bold.ttf"
    # Cuneiform and Hieroglyphs
    "NotoSansCuneiform-Bold.ttf"
    "NotoSansUgaritic-Bold.ttf"
    "NotoSansOldPersian-Bold.ttf"
    "NotoSansEgyptianHieroglyphs-Bold.ttf"
    "NotoSansMeroitic-Bold.ttf"
    "NotoSansAnatolianHieroglyphs-Bold.ttf"
    # Africa
    "NotoSansEthiopic-Bold.ttf"
    "NotoSansOsmanya-Bold.ttf"
    "NotoSansTifinagh-Bold.ttf" # TODO: check Tifinagh variants
    "NotoSansNKo-Bold.ttf"
    "NotoSansVai-Bold.ttf"
    "NotoSansMendeKikakui-Bold.ttf"
    "NotoSansMedefaidrin-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoSouthAsia=(
    "NotoSans-Bold.ttf"
    "NotoNastaliqUrdu-Bold.ttf"
    "NotoSansBengali-Bold.ttf"
    "NotoSansChakma-Bold.ttf"
    "NotoSansDevanagari-Bold.ttf"
    "NotoSansGujarati-Bold.ttf"
    "NotoSansGunjalaGondi-Bold.ttf"
    "NotoSansGurmukhi-Bold.ttf"
    "NotoSansKannada-Bold.ttf"
    "NotoSansLepcha-Bold.ttf"
    "NotoSansLimbu-Bold.ttf"
    "NotoSansMalayalam-Bold.ttf"
    "NotoSansMasaramGondi-Bold.ttf"
    "NotoSansMeeteiMayek-Bold.ttf"
    "NotoSansMro-Bold.ttf"
    "NotoSansNewa-Bold.ttf"
    "NotoSansOlChiki-Bold.ttf"
    "NotoSansOriya-Bold.ttf"
    "NotoSansSaurashtra-Bold.ttf"
    "NotoSansSinhala-Bold.ttf"
    "NotoSansTamil-Bold.ttf"
    "NotoSansTangsa-Bold.ttf"
    "NotoSansTelugu-Bold.ttf"
    "NotoSansThaana-Bold.ttf"
    "NotoSerifTibetanSubset-Bold.ttf"
    "NotoSerifToto-Bold.ttf"
    "NotoSansWancho-Bold.ttf"
    "NotoSansWarangCiti-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoAsiaHistorical=(
    "NotoSans-Bold.ttf"
    "NotoSansBhaiksuki-Bold.ttf"
    "NotoSansBrahmi-Bold.ttf"
    "NotoSansGrantha-Bold.ttf"
    "NotoSansKaithi-Bold.ttf"
    "NotoSansKharoshthi-Bold.ttf"
    "NotoSansKhudawadi-Bold.ttf"
    "NotoSansMahajani-Bold.ttf"
    "NotoSansMarchen-Bold.ttf"
    "NotoSansModi-Bold.ttf"
    "NotoSansMultani-Bold.ttf"
    "NotoSansNandinagariSubset-Bold.ttf"
    "NotoSansOldSogdian-Bold.ttf"
    "NotoSansOldTurkic-Bold.ttf"
    "NotoSansPhags-Pa-Bold.ttf"
    "NotoSansSharada-Bold.ttf"
    "NotoSansSiddham-Bold.ttf"
    "NotoSansSogdian-Bold.ttf"
    "NotoSansSoraSompeng-Bold.ttf"
    "NotoSansSoyombo-Bold.ttf"
    "NotoSansSylotiNagri-Bold.ttf"
    "NotoSansTakri-Bold.ttf"
    "NotoSansTirhuta-Bold.ttf"
    "NotoSansZanabazarSquare-Bold.ttf"
    "NotoSansIndicSiyaqNumbers-Bold.ttf"
    "NotoSerifAhom-Bold.ttf"
    "NotoSerifDograSubset-Bold.ttf"
    "NotoSerifKhojki-Bold.ttf"
    "NotoSerifOldUyghur-Bold.ttf"
    "NotoSerifDivesAkuru-Bold.ttf"
    "NotoSerifMakasar-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoSouthEastAsia=(
    "NotoSans-Bold.ttf"
    "NotoSansBalinese-Bold.ttf"
    "NotoSansBatak-Bold.ttf"
    "NotoSansBuginese-Bold.ttf"
    "NotoSansBuhid-Bold.ttf"
    "NotoSansCham-Bold.ttf"
    "NotoSansHanifiRohingya-Bold.ttf"
    "NotoSansHanunoo-Bold.ttf"
    "NotoSansJavanese-Bold.ttf"
    "NotoSansKayahLi-Bold.ttf"
    "NotoSansKhmer-Bold.ttf"
    "NotoSansLao-Bold.ttf"
    "NotoSansMyanmar-Bold.ttf"
    "NotoSansNewTaiLue-Bold.ttf"
    "NotoSansPahawhHmong-Bold.ttf"
    "NotoSerifNyiakengPuachueHmong-Bold.ttf"
    "NotoSansPauCinHau-Bold.ttf"
    "NotoSansRejang-Bold.ttf"
    "NotoSansSundanese-Bold.ttf"
    "NotoSansTagalog-Bold.ttf"
    "NotoSansTagbanwa-Bold.ttf"
    "NotoSansTaiLe-Bold.ttf"
    "NotoSansTaiTham-Bold.ttf"
    "NotoSansTaiViet-Bold.ttf"
    "NotoSansThai-Bold.ttf"
    "NotoSerifMakasar-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoEastAsia=(
    "NotoSans-Bold.ttf"
    "NotoSansMarchen-Bold.ttf"
    "NotoSansMongolianSubset-Bold.ttf"
    "NotoSansOldSogdian-Bold.ttf"
    "NotoSansOldTurkic-Bold.ttf"
    "NotoSansPhags-Pa-Bold.ttf"
    "NotoSansSogdian-Bold.ttf"
    "NotoSansSoyombo-Bold.ttf"
    "NotoSansZanabazarSquare-Bold.ttf"
    "NotoSerifTibetanSubset-Bold.ttf"
    "NotoSansYi-Bold.ttf"
    "NotoSansNushuSubset-Bold.ttf"
    "NotoSansLisu-Bold.ttf"
    "NotoSansMiao-Bold.ttf"
    "NotoSerifTangutSubset-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoEuropeAmericas=(
    "NotoSans-Bold.ttf"
    "NotoSansArmenian-Bold.ttf"
    "NotoSansCherokee-Bold.ttf"
    "NotoSansCoptic-Bold.ttf"
    "NotoSansDeseret-Bold.ttf"
    "NotoSansGeorgian-Bold.ttf"
    "NotoSansGlagolitic-Bold.ttf"
    "NotoSansOsage-Bold.ttf"
    "NotoSansSignWriting-Bold.ttf"
    "NotoSerifNyiakengPuachueHmong-Bold.ttf"
    # Historical
    "NotoSansCypriot-Bold.ttf"
    "NotoSansCyproMinoan-Bold.ttf"
    "NotoSansCaucasianAlbanian-Bold.ttf"
    "NotoSansCarian-Bold.ttf"
    "NotoSansCanadianAboriginal-Bold.ttf"
    "NotoSansLinearA-Bold.ttf"
    "NotoSansLinearB-Bold.ttf"
    "NotoSansLycian-Bold.ttf"
    "NotoSansLydian-Bold.ttf"
    "NotoSansAnatolianHieroglyphs-Bold.ttf"
    "NotoSansOldItalic-Bold.ttf"
    "NotoSansRunic-Bold.ttf"
    "NotoSansOldHungarian-Bold.ttf"
    "NotoSansGothic-Bold.ttf"
    "NotoSansElbasan-Bold.ttf"
    "NotoSansVithkuqi-Bold.ttf"
    "NotoSansOgham-Bold.ttf"
    "NotoSansOldPermic-Bold.ttf"
    "NotoSansShavian-Bold.ttf"
    "NotoSansDuployan-Bold.ttf"
    "NotoSansMayanNumerals-Bold.ttf"
    # Common for all scripts
    "NotoSansSymbols-Bold.ttf"
    "NotoSansSymbols2-Bold.ttf"
    "NotoSansMath-Bold.ttf"
    "NotoMusic-Bold.ttf"
)

GoNotoAncientSerif=(
    "NotoSerif-Bold.ttf"
    "NotoSerifAhom-Bold.ttf"
    "NotoSerifDogra-Bold.ttf"
    "NotoSerifGrantha-Bold.ttf"
    "NotoSerifKhojki-Bold.ttf"
    "NotoSerifNyiakengPuachueHmong-Bold.ttf"
    "NotoSerifOldUyghur-Bold.ttf"
    "NotoSerifTangut-Bold.ttf"
    "NotoSerifVithkuqi-Bold.ttf"
    "NotoSerifDivesAkuru-Bold.ttf"
    "NotoSerifMakasar-Bold.ttf"
)

GoNotoCurrentSerif=(
    "NotoSerif-Bold.ttf"
    "NotoNaskhArabic-Bold.ttf"  # not really "serif" but any Arabic would do
    "NotoSerifArmenian-Bold.ttf"
    "NotoSerifBalinese-Bold.ttf"
    "NotoSerifBengali-Bold.ttf"
    "NotoSerifDevanagari-Bold.ttf"
    "NotoSerifEthiopic-Bold.ttf"
    "NotoSerifGeorgian-Bold.ttf"
    "NotoSerifGujarati-Bold.ttf"
    "NotoSerifGurmukhi-Bold.ttf"
    "NotoSerifHebrew-Bold.ttf"
    "NotoSerifKannada-Bold.ttf"
    "NotoSerifKhmer-Bold.ttf"
    "NotoSerifLao-Bold.ttf"
    "NotoSerifMalayalam-Bold.ttf"
    "NotoSerifMyanmar-Bold.ttf"
    "NotoSerifOriya-Bold.ttf"
    "NotoSerifSinhala-Bold.ttf"
    "NotoSerifTamil-Bold.ttf"
    "NotoSerifTelugu-Bold.ttf"
    "NotoSerifThai-Bold.ttf"
    "NotoSerifTibetanSubset-Bold.ttf"  # non-"Subset" also works but takes a long time
    "NotoSerifToto-Bold.ttf"
    "NotoSerifYezidi-Bold.ttf"
    # Common for all scripts (even though not serif)
    # TODO Enabling these injects sans-serif variant of Latin alphabet
#    "NotoSansSymbols-Bold.ttf"
#    "NotoSansSymbols2-Bold.ttf"
#    "NotoSansMath-Bold.ttf"
#    "NotoMusic-Bold.ttf"
)
