#!/usr/bin/env bash
set -eu

# URL:s taken from https://notofonts.github.io/

# Associative array (key-value pair)
# Sorted alphabetically as per keys

# Those fonts NOT directly under notofonts.github.io/fonts/
# are not yet migrated fully (apparently) and hence development build URLs are used below

# Problematic/unavailable URLs are marked TODO
declare -A font_urls=(
    ["NotoMusic-Bold.ttf"]=https://notofonts.github.io/music/fonts/NotoMusic/hinted/ttf/NotoMusic-Bold.ttf
    ["NotoNaskhArabic-Bold.ttf"]=https://notofonts.github.io/fonts/NotoNaskhArabic/hinted/ttf/NotoNaskhArabic-Bold.ttf
    ["NotoNastaliqUrdu-Bold.ttf"]=https://notofonts.github.io/fonts/NotoNastaliqUrdu/hinted/ttf/NotoNastaliqUrdu-Bold.ttf
    ["NotoSansAdlam-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansAdlam/hinted/ttf/NotoSansAdlam-Bold.ttf
    ["NotoSansAnatolianHieroglyphs-Bold.ttf"]=https://notofonts.github.io/anatolian-hieroglyphs/fonts/NotoSansAnatolianHieroglyphs/hinted/ttf/NotoSansAnatolianHieroglyphs-Bold.ttf
    ["NotoSansArabic-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansArabic/hinted/ttf/NotoSansArabic-Bold.ttf
    ["NotoSansArmenian-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansArmenian/hinted/ttf/NotoSansArmenian-Bold.ttf
    ["NotoSansAvestan-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansAvestan/hinted/ttf/NotoSansAvestan-Bold.ttf
    ["NotoSansBalinese-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansBalinese/hinted/ttf/NotoSansBalinese-Bold.ttf
    ["NotoSansBamum-Bold.ttf"]=https://notofonts.github.io/bamum/fonts/NotoSansBamum/hinted/ttf/NotoSansBamum-Bold.ttf
    ["NotoSansBassaVah-Bold.ttf"]=https://notofonts.github.io/bassa-vah/fonts/NotoSansBassaVah/hinted/ttf/NotoSansBassaVah-Bold.ttf
    ["NotoSansBatak-Bold.ttf"]=https://notofonts.github.io/batak/fonts/NotoSansBatak/hinted/ttf/NotoSansBatak-Bold.ttf
    ["NotoSansBengali-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansBengali/hinted/ttf/NotoSansBengali-Bold.ttf
    ["NotoSansBhaiksuki-Bold.ttf"]=https://notofonts.github.io/bhaiksuki/fonts/NotoSansBhaiksuki-Bold/hinted/ttf/NotoSansBhaiksuki-Bold.ttf
    ["NotoSansBrahmi-Bold.ttf"]=https://notofonts.github.io/brahmi/fonts/NotoSansBrahmi/hinted/ttf/NotoSansBrahmi-Bold.ttf
    ["NotoSansBuginese-Bold.ttf"]=https://notofonts.github.io/buginese/fonts/NotoSansBuginese/hinted/ttf/NotoSansBuginese-Bold.ttf
    ["NotoSansBuhid-Bold.ttf"]=https://notofonts.github.io/buhid/fonts/NotoSansBuhid/hinted/ttf/NotoSansBuhid-Bold.ttf
    ["NotoSansCanadianAboriginal-Bold.ttf"]=https://notofonts.github.io/canadian-aboriginal/fonts/NotoSansCanadianAboriginal/hinted/ttf/NotoSansCanadianAboriginal-Bold.ttf
    ["NotoSansCarian-Bold.ttf"]=https://notofonts.github.io/carian/fonts/NotoSansCarian/hinted/ttf/NotoSansCarian-Bold.ttf
    ["NotoSansCaucasianAlbanian-Bold.ttf"]=https://notofonts.github.io/caucasian-albanian/fonts/NotoSansCaucasianAlbanian/hinted/ttf/NotoSansCaucasianAlbanian-Bold.ttf
    ["NotoSansChakma-Bold.ttf"]=https://notofonts.github.io/chakma/fonts/NotoSansChakma/hinted/ttf/NotoSansChakma-Bold.ttf
    ["NotoSansCham-Bold.ttf"]=https://notofonts.github.io/cham/fonts/NotoSansCham/hinted/ttf/NotoSansCham-Bold.ttf
    ["NotoSansCherokee-Bold.ttf"]=https://notofonts.github.io/cherokee/fonts/NotoSansCherokee/hinted/ttf/NotoSansCherokee-Bold.ttf
    ["NotoSansChorasmian-Bold.ttf"]=https://notofonts.github.io/chorasmian/fonts/NotoSansChorasmian/hinted/ttf/NotoSansChorasmian-Bold.ttf
    ["NotoSansCoptic-Bold.ttf"]=https://notofonts.github.io/coptic/fonts/NotoSansCoptic/hinted/ttf/NotoSansCoptic-Bold.ttf
    ["NotoSansCuneiform-Bold.ttf"]=https://notofonts.github.io/cuneiform/fonts/NotoSansCuneiform/hinted/ttf/NotoSansCuneiform-Bold.ttf
    ["NotoSansCypriot-Bold.ttf"]=https://notofonts.github.io/cypriot/fonts/NotoSansCypriot/hinted/ttf/NotoSansCypriot-Bold.ttf
    ["NotoSansCyproMinoan-Bold.ttf"]=https://notofonts.github.io/cypro-minoan/fonts/NotoSansCyproMinoan/hinted/ttf/NotoSansCyproMinoan-Bold.ttf
    ["NotoSansDeseret-Bold.ttf"]=https://notofonts.github.io/deseret/fonts/NotoSansDeseret/hinted/ttf/NotoSansDeseret-Bold.ttf
    ["NotoSansDevanagari-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansDevanagari/hinted/ttf/NotoSansDevanagari-Bold.ttf
    ["NotoSansDuployan-Bold.ttf"]=https://notofonts.github.io/duployan/fonts/NotoSansDuployan/hinted/ttf/NotoSansDuployan-Bold.ttf
    ["NotoSansEgyptianHieroglyphs-Bold.ttf"]=https://notofonts.github.io/egyptian-hieroglyphs/fonts/NotoSansEgyptianHieroglyphs/hinted/ttf/NotoSansEgyptianHieroglyphs-Bold.ttf
    ["NotoSansElbasan-Bold.ttf"]=https://notofonts.github.io/elbasan/fonts/NotoSansElbasan/hinted/ttf/NotoSansElbasan-Bold.ttf
    ["NotoSansElymaic-Bold.ttf"]=https://notofonts.github.io/elymaic/fonts/NotoSansElymaic/hinted/ttf/NotoSansElymaic-Bold.ttf
    ["NotoSansEthiopic-Bold.ttf"]=https://notofonts.github.io/ethiopic/fonts/NotoSansEthiopic/hinted/ttf/NotoSansEthiopic-Bold.ttf
    ["NotoSansGeorgian-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansGeorgian/hinted/ttf/NotoSansGeorgian-Bold.ttf
    ["NotoSansGlagolitic-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansGlagolitic/hinted/ttf/NotoSansGlagolitic-Bold.ttf
    ["NotoSansGothic-Bold.ttf"]=https://notofonts.github.io/gothic/fonts/NotoSansGothic/hinted/ttf/NotoSansGothic-Bold.ttf
    ["NotoSansGrantha-Bold.ttf"]=https://notofonts.github.io/grantha/fonts/NotoSansGrantha/hinted/ttf/NotoSansGrantha-Bold.ttf
    ["NotoSansGujarati-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansGujarati/hinted/ttf/NotoSansGujarati-Bold.ttf
    ["NotoSansGunjalaGondi-Bold.ttf"]=https://notofonts.github.io/gunjala-gondi/fonts/NotoSansGunjalaGondi/hinted/ttf/NotoSansGunjalaGondi-Bold.ttf
    ["NotoSansGurmukhi-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansGurmukhi/hinted/ttf/NotoSansGurmukhi-Bold.ttf
    ["NotoSansHanifiRohingya-Bold.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansHanifiRohingya/NotoSansHanifiRohingya-Bold.ttf # TODO
    ["NotoSansHanunoo-Bold.ttf"]=https://notofonts.github.io/hanunoo/fonts/NotoSansHanunoo/hinted/ttf/NotoSansHanunoo-Bold.ttf
    ["NotoSansHatran-Bold.ttf"]=https://notofonts.github.io/hatran/fonts/NotoSansHatran/hinted/ttf/NotoSansHatran-Bold.ttf
    ["NotoSansHebrew-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansHebrew/hinted/ttf/NotoSansHebrew-Bold.ttf
    ["NotoSansImperialAramaic-Bold.ttf"]=https://notofonts.github.io/imperial-aramaic/fonts/NotoSansImperialAramaic/hinted/ttf/NotoSansImperialAramaic-Bold.ttf
    ["NotoSansIndicSiyaqNumbers-Bold.ttf"]=https://notofonts.github.io/indic-siyaq-numbers/fonts/NotoSansIndicSiyaqNumbers/hinted/ttf/NotoSansIndicSiyaqNumbers-Bold.ttf
    ["NotoSansInscriptionalPahlavi-Bold.ttf"]=https://notofonts.github.io/inscriptional-pahlavi/fonts/NotoSansInscriptionalPahlavi/hinted/ttf/NotoSansInscriptionalPahlavi-Bold.ttf
    ["NotoSansInscriptionalParthian-Bold.ttf"]=https://notofonts.github.io/inscriptional-parthian/fonts/NotoSansInscriptionalParthian/hinted/ttf/NotoSansInscriptionalParthian-Bold.ttf
    ["NotoSansJavanese-Bold.ttf"]=https://notofonts.github.io/javanese/fonts/NotoSansJavanese/hinted/ttf/NotoSansJavanese-Bold.ttf
    ["NotoSansKaithi-Bold.ttf"]=https://notofonts.github.io/kaithi/fonts/NotoSansKaithi/hinted/ttf/NotoSansKaithi-Bold.ttf
    ["NotoSansKannada-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansKannada/hinted/ttf/NotoSansKannada-Bold.ttf
    ["NotoSansKayahLi-Bold.ttf"]=https://notofonts.github.io/kayah-li/fonts/NotoSansKayahLi/hinted/ttf/NotoSansKayahLi-Bold.ttf
    ["NotoSansKharoshthi-Bold.ttf"]=https://notofonts.github.io/kharoshthi/fonts/NotoSansKharoshthi/hinted/ttf/NotoSansKharoshthi-Bold.ttf
    ["NotoSansKhmer-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansKhmer/hinted/ttf/NotoSansKhmer-Bold.ttf
    ["NotoSansKhudawadi-Bold.ttf"]=https://notofonts.github.io/khudawadi/fonts/NotoSansKhudawadi/hinted/ttf/NotoSansKhudawadi-Bold.ttf
    ["NotoSansLao-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansLao/hinted/ttf/NotoSansLao-Bold.ttf
    ["NotoSansLepcha-Bold.ttf"]=https://notofonts.github.io/lepcha/fonts/NotoSansLepcha/hinted/ttf/NotoSansLepcha-Bold.ttf
    ["NotoSansLimbu-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansLimbu/hinted/ttf/NotoSansLimbu-Bold.ttf
    ["NotoSansLinearA-Bold.ttf"]=https://notofonts.github.io/linear-a/fonts/NotoSansLinearA/hinted/ttf/NotoSansLinearA-Bold.ttf
    ["NotoSansLinearB-Bold.ttf"]=https://notofonts.github.io/linear-b/fonts/NotoSansLinearB/hinted/ttf/NotoSansLinearB-Bold.ttf
    ["NotoSansLisu-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansLisu/hinted/ttf/NotoSansLisu-Bold.ttf
    ["NotoSansLycian-Bold.ttf"]=https://notofonts.github.io/lycian/fonts/NotoSansLycian/hinted/ttf/NotoSansLycian-Bold.ttf
    ["NotoSansLydian-Bold.ttf"]=https://notofonts.github.io/lydian/fonts/NotoSansLydian/hinted/ttf/NotoSansLydian-Bold.ttf
    ["NotoSansMahajani-Bold.ttf"]=https://notofonts.github.io/mahajani/fonts/NotoSansMahajani/hinted/ttf/NotoSansMahajani-Bold.ttf
    ["NotoSansMalayalam-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansMalayalam/hinted/ttf/NotoSansMalayalam-Bold.ttf
    ["NotoSansMandaic-Bold.ttf"]=https://notofonts.github.io/mandaic/fonts/NotoSansMandaic/hinted/ttf/NotoSansMandaic-Bold.ttf
    ["NotoSansManichaean-Bold.ttf"]=https://notofonts.github.io/manichaean/fonts/NotoSansManichaean/hinted/ttf/NotoSansManichaean-Bold.ttf
    ["NotoSansMarchen-Bold.ttf"]=https://notofonts.github.io/marchen/fonts/NotoSansMarchen/hinted/ttf/NotoSansMarchen-Bold.ttf
    ["NotoSansMasaramGondi-Bold.ttf"]=https://notofonts.github.io/masaram-gondi/fonts/NotoSansMasaramGondi/hinted/ttf/NotoSansMasaramGondi-Bold.ttf
    ["NotoSansMath-Bold.ttf"]=https://notofonts.github.io/math/fonts/NotoSansMath/hinted/ttf/NotoSansMath-Bold.ttf
    ["NotoSansMayanNumerals-Bold.ttf"]=https://notofonts.github.io/mayan-numerals/fonts/NotoSansMayanNumerals/hinted/ttf/NotoSansMayanNumerals-Bold.ttf
    ["NotoSansMedefaidrin-Bold.ttf"]=https://notofonts.github.io/medefaidrin/fonts/NotoSansMedefaidrin/hinted/ttf/NotoSansMedefaidrin-Bold.ttf
    ["NotoSansMeeteiMayek-Bold.ttf"]=https://notofonts.github.io/meetei-mayek/fonts/NotoSansMeeteiMayek/hinted/ttf/NotoSansMeeteiMayek-Bold.ttf
    ["NotoSansMendeKikakui-Bold.ttf"]=https://notofonts.github.io/mende-kikakui/fonts/NotoSansMendeKikakui/hinted/ttf/NotoSansMendeKikakui-Bold.ttf
    ["NotoSansMeroitic-Bold.ttf"]=https://notofonts.github.io/meroitic/fonts/NotoSansMeroitic/hinted/ttf/NotoSansMeroitic-Bold.ttf
    ["NotoSansMiao-Bold.ttf"]=https://notofonts.github.io/miao/fonts/NotoSansMiao/hinted/ttf/NotoSansMiao-Bold.ttf
    ["NotoSansModi-Bold.ttf"]=https://notofonts.github.io/modi/fonts/NotoSansModi/hinted/ttf/NotoSansModi-Bold.ttf
    ["NotoSansMongolian-Regular.ttf"]=https://notofonts.github.io/mongolian/fonts/NotoSansMongolian/hinted/ttf/NotoSansMongolian-Regular.ttf
    ["NotoSansMro-Bold.ttf"]=https://notofonts.github.io/mro/fonts/NotoSansMro/hinted/ttf/NotoSansMro-Bold.ttf
    ["NotoSansMultani-Bold.ttf"]=https://notofonts.github.io/multani/fonts/NotoSansMultani/hinted/ttf/NotoSansMultani-Bold.ttf
    ["NotoSansMyanmar-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansMyanmar/hinted/ttf/NotoSansMyanmar-Bold.ttf
    ["NotoSansNabataean-Bold.ttf"]=https://notofonts.github.io/nabataean/fonts/NotoSansNabataean/hinted/ttf/NotoSansNabataean-Bold.ttf
    ["NotoSansNandinagari-Bold.ttf"]=https://notofonts.github.io/nandinagari/fonts/NotoSansNandinagari/hinted/ttf/NotoSansNandinagari-Bold.ttf
    ["NotoSansNewa-Bold.ttf"]=https://notofonts.github.io/newa/fonts/NotoSansNewa/hinted/ttf/NotoSansNewa-Bold.ttf
    ["NotoSansNewTaiLue-Bold.ttf"]=https://notofonts.github.io/new-tai-lue/fonts/NotoSansNewTaiLue/hinted/ttf/NotoSansNewTaiLue-Bold.ttf
    ["NotoSansNKo-Bold.ttf"]=https://notofonts.github.io/nko/fonts/NotoSansNKo/hinted/ttf/NotoSansNKo-Bold.ttf
    ["NotoSansNushu-Regular.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansNushu/NotoSansNushu-Bold.ttf # TODO
    ["NotoSansOgham-Bold.ttf"]=https://notofonts.github.io/ogham/fonts/NotoSansOgham/hinted/ttf/NotoSansOgham-Bold.ttf
    ["NotoSansOlChiki-Bold.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansOlChiki/NotoSansOlChiki-Bold.ttf # TODO
    ["NotoSansOldHungarian-Bold.ttf"]=https://notofonts.github.io/old-hungarian/fonts/NotoSansOldHungarian/hinted/ttf/NotoSansOldHungarian-Bold.ttf
    ["NotoSansOldItalic-Bold.ttf"]=https://notofonts.github.io/old-italic/fonts/NotoSansOldItalic/hinted/ttf/NotoSansOldItalic-Bold.ttf
    ["NotoSansOldNorthArabian-Bold.ttf"]=https://notofonts.github.io/old-north-arabian/fonts/NotoSansOldNorthArabian/hinted/ttf/NotoSansOldNorthArabian-Bold.ttf
    ["NotoSansOldPermic-Bold.ttf"]=https://notofonts.github.io/old-permic/fonts/NotoSansOldPermic/hinted/ttf/NotoSansOldPermic-Bold.ttf
    ["NotoSansOldPersian-Bold.ttf"]=https://notofonts.github.io/old-persian/fonts/NotoSansOldPersian/hinted/ttf/NotoSansOldPersian-Bold.ttf
    ["NotoSansOldSogdian-Bold.ttf"]=https://notofonts.github.io/old-sogdian/fonts/NotoSansOldSogdian/hinted/ttf/NotoSansOldSogdian-Bold.ttf
    ["NotoSansOldSouthArabian-Bold.ttf"]=https://notofonts.github.io/old-south-arabian/fonts/NotoSansOldSouthArabian/hinted/ttf/NotoSansOldSouthArabian-Bold.ttf
    ["NotoSansOldTurkic-Bold.ttf"]=https://notofonts.github.io/old-turkic/fonts/NotoSansOldTurkic/hinted/ttf/NotoSansOldTurkic-Bold.ttf
    ["NotoSansOriya-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansOriya/hinted/ttf/NotoSansOriya-Bold.ttf
    ["NotoSansOsage-Bold.ttf"]=https://notofonts.github.io/osage/fonts/NotoSansOsage/hinted/ttf/NotoSansOsage-Bold.ttf
    ["NotoSansOsmanya-Bold.ttf"]=https://notofonts.github.io/osmanya/fonts/NotoSansOsmanya/hinted/ttf/NotoSansOsmanya-Bold.ttf
    ["NotoSansPahawhHmong-Bold.ttf"]=https://notofonts.github.io/pahawh-hmong/fonts/NotoSansPahawhHmong/hinted/ttf/NotoSansPahawhHmong-Bold.ttf
    ["NotoSansPalmyrene-Bold.ttf"]=https://notofonts.github.io/palmyrene/fonts/NotoSansPalmyrene/hinted/ttf/NotoSansPalmyrene-Bold.ttf
    ["NotoSansPauCinHau-Bold.ttf"]=https://notofonts.github.io/pau-cin-hau/fonts/NotoSansPauCinHau/hinted/ttf/NotoSansPauCinHau-Bold.ttf
    ["NotoSansPhags-Pa-Bold.ttf"]=https://notofonts.github.io//fonts/NotoSansPhagsPa/hinted/ttf/NotoSansPhags-Pa-Bold.ttf # // likely erroneous
    ["NotoSansPhoenician-Bold.ttf"]=https://notofonts.github.io/phoenician/fonts/NotoSansPhoenician/hinted/ttf/NotoSansPhoenician-Bold.ttf
    ["NotoSansPsalterPahlavi-Bold.ttf"]=https://notofonts.github.io/psalter-pahlavi/fonts/NotoSansPsalterPahlavi/hinted/ttf/NotoSansPsalterPahlavi-Bold.ttf
    ["NotoSans-Bold.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Bold.ttf # TODO
    ["NotoSansRejang-Bold.ttf"]=https://notofonts.github.io/rejang/fonts/NotoSansRejang/hinted/ttf/NotoSansRejang-Bold.ttf
    ["NotoSansRunic-Bold.ttf"]=https://notofonts.github.io/runic/fonts/NotoSansRunic/hinted/ttf/NotoSansRunic-Bold.ttf
    ["NotoSansSamaritan-Bold.ttf"]=https://notofonts.github.io/samaritan/fonts/NotoSansSamaritan/hinted/ttf/NotoSansSamaritan-Bold.ttf
    ["NotoSansSaurashtra-Bold.ttf"]=https://notofonts.github.io/saurashtra/fonts/NotoSansSaurashtra/hinted/ttf/NotoSansSaurashtra-Bold.ttf
    ["NotoSansSharada-Bold.ttf"]=https://notofonts.github.io/sharada/fonts/NotoSansSharada/hinted/ttf/NotoSansSharada-Bold.ttf
    ["NotoSansShavian-Bold.ttf"]=https://notofonts.github.io/shavian/fonts/NotoSansShavian/hinted/ttf/NotoSansShavian-Bold.ttf
    ["NotoSansSiddham-Bold.ttf"]=https://notofonts.github.io/siddham/fonts/NotoSansSiddham/hinted/ttf/NotoSansSiddham-Bold.ttf
    ["NotoSansSignWriting-Bold.ttf"]=https://notofonts.github.io/sign-writing/fonts/NotoSansSignWriting/hinted/ttf/NotoSansSignWriting-Bold.ttf
    ["NotoSansSinhala-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansSinhala/hinted/ttf/NotoSansSinhala-Bold.ttf
    ["NotoSansSogdian-Bold.ttf"]=https://notofonts.github.io/sogdian/fonts/NotoSansSogdian/hinted/ttf/NotoSansSogdian-Bold.ttf
    ["NotoSansSoraSompeng-Bold.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansSoraSompeng/NotoSansSoraSompeng-Bold.ttf # TODO
    ["NotoSansSoyombo-Bold.ttf"]=https://notofonts.github.io/soyombo/fonts/NotoSansSoyombo/hinted/ttf/NotoSansSoyombo-Bold.ttf
    ["NotoSansSundanese-Bold.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSansSundanese/NotoSansSundanese-Bold.ttf # TODO
    ["NotoSansSylotiNagri-Bold.ttf"]=https://notofonts.github.io/syloti-nagri/fonts/NotoSansSylotiNagri/hinted/ttf/NotoSansSylotiNagri-Bold.ttf
    ["NotoSansSymbols2-Bold.ttf"]=https://notofonts.github.io/symbols/fonts/NotoSansSymbols2/hinted/ttf/NotoSansSymbols2-Bold.ttf
    ["NotoSansSymbols-Bold.ttf"]=https://notofonts.github.io/symbols/fonts/NotoSansSymbols/hinted/ttf/NotoSansSymbols-Bold.ttf
    ["NotoSansSyriac-Bold.ttf"]=https://notofonts.github.io/syriac/fonts/NotoSansSyriac-Bold/hinted/ttf/NotoSansSyriac-Bold.ttf
    ["NotoSansTagalog-Bold.ttf"]=https://notofonts.github.io/tagalog/fonts/NotoSansTagalog/hinted/ttf/NotoSansTagalog-Bold.ttf
    ["NotoSansTagbanwa-Bold.ttf"]=https://notofonts.github.io/tagbanwa/fonts/NotoSansTagbanwa/hinted/ttf/NotoSansTagbanwa-Bold.ttf
    ["NotoSansTaiLe-Bold.ttf"]=https://notofonts.github.io/tai-le/fonts/NotoSansTaiLe/hinted/ttf/NotoSansTaiLe-Bold.ttf
    ["NotoSansTaiTham-Bold.ttf"]=https://notofonts.github.io/tai-tham/fonts/NotoSansTaiTham/hinted/ttf/NotoSansTaiTham-Bold.ttf
    ["NotoSansTaiViet-Bold.ttf"]=https://notofonts.github.io/tai-viet/fonts/NotoSansTaiViet/hinted/ttf/NotoSansTaiViet-Bold.ttf
    ["NotoSansTakri-Bold.ttf"]=https://notofonts.github.io/takri/fonts/NotoSansTakri/hinted/ttf/NotoSansTakri-Bold.ttf
    ["NotoSansTamil-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansTamil/hinted/ttf/NotoSansTamil-Bold.ttf
    ["NotoSansTangsa-Bold.ttf"]=https://notofonts.github.io/tangsa/fonts/NotoSansTangsa/hinted/ttf/NotoSansTangsa-Bold.ttf
    ["NotoSansTelugu-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansTelugu/hinted/ttf/NotoSansTelugu-Bold.ttf
    ["NotoSansThaana-Bold.ttf"]=https://notofonts.github.io/thaana/fonts/NotoSansThaana/hinted/ttf/NotoSansThaana-Bold.ttf
    ["NotoSansThai-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansThai/hinted/ttf/NotoSansThai-Bold.ttf
    ["NotoSansTifinagh-Bold.ttf"]=https://notofonts.github.io/tifinagh/fonts/NotoSansTifinagh/hinted/ttf/NotoSansTifinagh-Bold.ttf
    ["NotoSansTirhuta-Bold.ttf"]=https://notofonts.github.io/tirhuta/fonts/NotoSansTirhuta/hinted/ttf/NotoSansTirhuta-Bold.ttf
    ["NotoSansUgaritic-Bold.ttf"]=https://notofonts.github.io/ugaritic/fonts/NotoSansUgaritic/hinted/ttf/NotoSansUgaritic-Bold.ttf
    ["NotoSansVai-Bold.ttf"]=https://notofonts.github.io/vai/fonts/NotoSansVai/hinted/ttf/NotoSansVai-Bold.ttf
    ["NotoSansVithkuqi-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSansVithkuqi/hinted/ttf/NotoSansVithkuqi-Bold.ttf
    ["NotoSansWancho-Bold.ttf"]=https://notofonts.github.io/wancho/fonts/NotoSansWancho/hinted/ttf/NotoSansWancho-Bold.ttf
    ["NotoSansWarangCiti-Bold.ttf"]=https://notofonts.github.io/warang-citi/fonts/NotoSansWarangCiti/hinted/ttf/NotoSansWarangCiti-Bold.ttf
    ["NotoSansYi-Bold.ttf"]=https://notofonts.github.io/yi/fonts/NotoSansYi/hinted/ttf/NotoSansYi-Bold.ttf
    ["NotoSansZanabazarSquare-Bold.ttf"]=https://notofonts.github.io/zanabazar-square/fonts/NotoSansZanabazarSquare/hinted/ttf/NotoSansZanabazarSquare-Bold.ttf
    ["NotoSerifAhom-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifAhom/hinted/ttf/NotoSerifAhom-Bold.ttf
    ["NotoSerifArmenian-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifArmenian/hinted/ttf/NotoSerifArmenian-Bold.ttf
    ["NotoSerifBalinese-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifBalinese/hinted/ttf/NotoSerifBalinese-Bold.ttf
    ["NotoSerifBengali-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifBengali/hinted/ttf/NotoSerifBengali-Bold.ttf
    ["NotoSerifDevanagari-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifDevanagari/hinted/ttf/NotoSerifDevanagari-Bold.ttf
    ["NotoSerifDivesAkuru-Bold.ttf"]=https://notofonts.github.io/dives-akuru/fonts/NotoSerifDivesAkuru/hinted/ttf/NotoSerifDivesAkuru-Bold.ttf
    ["NotoSerifDogra-Bold.ttf"]=https://notofonts.github.io/dogra/fonts/NotoSerifDogra/hinted/ttf/NotoSerifDogra-Bold.ttf
    ["NotoSerifEthiopic-Bold.ttf"]=https://notofonts.github.io/ethiopic/fonts/NotoSerifEthiopic/hinted/ttf/NotoSerifEthiopic-Bold.ttf
    ["NotoSerifGeorgian-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifGeorgian/hinted/ttf/NotoSerifGeorgian-Bold.ttf
    ["NotoSerifGrantha-Bold.ttf"]=https://notofonts.github.io/grantha/fonts/NotoSerifGrantha/hinted/ttf/NotoSerifGrantha-Bold.ttf
    ["NotoSerifGujarati-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifGujarati/hinted/ttf/NotoSerifGujarati-Bold.ttf
    ["NotoSerifGurmukhi-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifGurmukhi/hinted/ttf/NotoSerifGurmukhi-Bold.ttf
    ["NotoSerifHebrew-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifHebrew/hinted/ttf/NotoSerifHebrew-Bold.ttf
    ["NotoSerifKannada-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifKannada/hinted/ttf/NotoSerifKannada-Bold.ttf
    ["NotoSerifKhmer-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifKhmer/hinted/ttf/NotoSerifKhmer-Bold.ttf
    ["NotoSerifKhojki-Bold.ttf"]=https://notofonts.github.io/khojki/fonts/NotoSerifKhojki/hinted/ttf/NotoSerifKhojki-Bold.ttf
    ["NotoSerifLao-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifLao/hinted/ttf/NotoSerifLao-Bold.ttf
    ["NotoSerifMakasar-Bold.ttf"]=https://notofonts.github.io/makasar/fonts/NotoSerifMakasar/hinted/ttf/NotoSerifMakasar-Bold.ttf
    ["NotoSerifMalayalam-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifMalayalam/hinted/ttf/NotoSerifMalayalam-Bold.ttf
    ["NotoSerifMyanmar-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifMyanmar/hinted/ttf/NotoSerifMyanmar-Bold.ttf
    ["NotoSerifNyiakengPuachueHmong-Bold.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSerifNyiakengPuachueHmong/NotoSerifNyiakengPuachueHmong-Bold.ttf # TODO
    ["NotoSerifOldUyghur-Bold.ttf"]=https://notofonts.github.io/old-uyghur/fonts/NotoSerifOldUyghur/hinted/ttf/NotoSerifOldUyghur-Bold.ttf
    ["NotoSerifOriya-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifOriya/hinted/ttf/NotoSerifOriya-Bold.ttf
    ["NotoSerif-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerif/hinted/ttf/NotoSerif-Bold.ttf
    ["NotoSerifSinhala-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifSinhala/hinted/ttf/NotoSerifSinhala-Bold.ttf
    ["NotoSerifTamil-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifTamil/hinted/ttf/NotoSerifTamil-Bold.ttf
    ["NotoSerifTangut-Bold.ttf"]=https://notofonts.github.io/tangut/fonts/NotoSerifTangut/hinted/ttf/NotoSerifTangut-Bold.ttf
    ["NotoSerifTelugu-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifTelugu/hinted/ttf/NotoSerifTelugu-Bold.ttf
    ["NotoSerifThai-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifThai/hinted/ttf/NotoSerifThai-Bold.ttf
    ["NotoSerifTibetan-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifTibetan/hinted/ttf/NotoSerifTibetan-Bold.ttf
    ["NotoSerifToto-Bold.ttf"]=https://notofonts.github.io/toto/fonts/NotoSerifToto/hinted/ttf/NotoSerifToto-Bold.ttf
    ["NotoSerifVithkuqi-Bold.ttf"]=https://notofonts.github.io/fonts/NotoSerifVithkuqi/hinted/ttf/NotoSerifVithkuqi-Bold.ttf
    ["NotoSerifYezidi-Bold.ttf"]=https://github.com/notofonts/noto-fonts/raw/main/hinted/ttf/NotoSerifYezidi/NotoSerifYezidi-Bold.ttf # TODO
)
